# Generated by Django 4.0.2 on 2022-02-16 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opensecuser',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
