# Generated by Django 4.0.2 on 2022-02-16 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Camera name')),
                ('rtsp_url', models.URLField(verbose_name='RTSP URL')),
                ('is_onvif', models.BooleanField(default=False, verbose_name='ONVIF compliant?')),
                ('is_ptz', models.BooleanField(default=False, verbose_name='Has PTZ controls?')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is the camera currently active?')),
                ('video_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Source video height')),
                ('video_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Source video width')),
                ('video_framerate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Source video framerate')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Camera addition date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Intruder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Intruder detection date')),
                ('label', models.CharField(default='Unknown', max_length=50, verbose_name='Auto-generated label')),
                ('video_path', models.FilePathField(blank=True, null=True, verbose_name='Video file path')),
                ('thumb_path', models.FilePathField(blank=True, null=True, verbose_name='Thumbnail file path')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opensec.camera', verbose_name='Camera the intruder was detected with')),
            ],
        ),
    ]
