# Generated by Django 4.0.2 on 2022-02-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intruder',
            name='thumb_path',
        ),
        migrations.RemoveField(
            model_name='intruder',
            name='video_path',
        ),
        migrations.AddField(
            model_name='intruder',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='intuder_thumbs', verbose_name='Intruder thumbnail'),
        ),
        migrations.AddField(
            model_name='intruder',
            name='video',
            field=models.FileField(blank=True, upload_to='intuder_videos', verbose_name='Video of intruder'),
        ),
    ]
