# Generated by Django 4.0.2 on 2022-02-17 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensec', '0002_remove_intruder_thumb_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='rtsp_url',
            field=models.URLField(validators=[django.core.validators.URLValidator(schemes=['rtsp', 'rtsps', 'rtspu'])], verbose_name='RTSP URL'),
        ),
    ]
