# Generated by Django 4.0.2 on 2022-02-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensec', '0004_alter_camera_rtsp_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='snapshot',
            field=models.ImageField(blank=True, upload_to='camera_snaps', verbose_name='Camera snapshot'),
        ),
    ]
