# Generated by Django 4.0.3 on 2022-03-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensec', '0008_alter_intruder_thumbnail_alter_intruder_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intruder',
            name='thumbnail',
            field=models.FilePathField(blank=True, verbose_name='Intruder thumbnail'),
        ),
        migrations.AlterField(
            model_name='intruder',
            name='video',
            field=models.FilePathField(blank=True, verbose_name='Video of intruder'),
        ),
    ]
