# Generated by Django 4.0.3 on 2022-03-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensec', '0010_remove_camera_video_framerate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='stream_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Link to camera stream'),
        ),
    ]
